name: Update Browserslist database

"on":
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-browserslist-database:
    name: Update Browserslist database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Update Browserslist database and create PR if applies
        uses: c2corg/browserslist-update-action@v2
        with:
          github_token: ${{ secrets.PAT }}
          branch: browserslist-update
          base_branch: main
          commit_message: |
            build: update Browserslist db
            
            Signed-off-by: GitHub Action <action@github.com>
          title: 'build: update Browserslist db'
          body: Auto-generated by [browserslist-update-action](https://github.com/c2corg/browserslist-update-action/)
          labels: 'dependencies'
